// Headless verification harness for the deterministic engine + speech-in-noise
// session logic.
//
//   dart run tool/verify/engine_harness.dart
//
// The golden vector below was generated by the REAL Python engine
// (packages/protocol_engine/engine.snr_staircase) and is asserted identically
// here and in tests/test_engine_golden.py, proving cross-language equivalence.
import 'dart:io';

import '../../lib/core/protocol_engine.dart';
import '../../lib/core/speech_in_noise.dart';

// --- Golden vector (from the Python snr_staircase) --------------------------
const List<bool> kSeq = [
  true, true, true, true, true, true, false, true, true, false, //
  false, true, true, false, true, true, false, false, true, true, //
  false, true, true, false,
];
const List<double> kTraj = [
  12, 10, 10, 8, 8, 6, 8, 8, 6, 8, //
  10, 10, 8, 10, 10, 8, 10, 12, 12, 10, //
  12, 12, 10, 12,
];
const List<double> kReversals = [6, 8, 6, 10, 8, 10, 8, 12, 10, 12, 10];
const double kThreshold = 62 / 6; // mean of last 6 reversals

int _checks = 0;
int _failures = 0;

void check(String name, bool condition) {
  _checks++;
  if (condition) {
    stdout.writeln('  ok   $name');
  } else {
    _failures++;
    stdout.writeln('  FAIL $name');
  }
}

bool listEqDouble(List<double> a, List<double> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i++) {
    if ((a[i] - b[i]).abs() > 1e-9) return false;
  }
  return true;
}

void main() {
  // 1) AdaptiveTrack matches the Python golden vector exactly.
  final track = AdaptiveTrack.snr();
  final traj = <double>[for (final c in kSeq) track.submit(c)];
  check('snr staircase trajectory matches golden', listEqDouble(traj, kTraj));
  check('reversals match golden', listEqDouble(track.reversals, kReversals));
  check('run is complete (>=8 reversals)', track.complete);
  check(
    'threshold matches golden',
    (track.threshold! - kThreshold).abs() < 1e-9,
  );
  check('threshold SD matches golden (precision)',
      (track.thresholdSd! - 1.3743685419).abs() < 1e-9);
  check('trials counter equals sequence length', track.trials == kSeq.length);

  // 2) Named constructors mirror the Python factories' bounds.
  final gap = AdaptiveTrack.gap();
  check('gap staircase bounds', gap.min == 0.5 && gap.max == 100);
  final mod = AdaptiveTrack.modulation();
  check('modulation staircase bounds', mod.min == -40 && mod.max == 0);

  // 2b) Levitt step-reduction golden (gap staircase: step 4 -> 1 over 2
  // reversals). Identical numbers are asserted in tests/test_engine_golden.py.
  const kGapTraj = <double>[
    20, 16, 16, 12, 12, 8, 10, 10, 9, 10, //
    11, 11, 10, 11, 11, 10, 11, 12, 12, 11, //
    12, 12, 11, 12,
  ];
  const kGapReversals = <double>[8, 10, 9, 11, 10, 11, 10, 12, 11, 12, 11];
  final gapGolden = AdaptiveTrack.gap();
  final gapTraj = <double>[for (final c in kSeq) gapGolden.submit(c)];
  check('gap step-reduction trajectory matches golden',
      listEqDouble(gapTraj, kGapTraj));
  check('gap reversals match golden',
      listEqDouble(gapGolden.reversals, kGapReversals));
  check('gap threshold matches golden (67/6)',
      (gapGolden.threshold! - 67 / 6).abs() < 1e-9);
  check('gap threshold SD matches golden (precision)',
      (gapGolden.thresholdSd! - 0.6871842709).abs() < 1e-9);
  check('gap step reduced to its 1 ms floor', gapGolden.currentStep == 1);

  // 2c) Frequency staircase reduction: 6 -> 4 (down by 2) -> 5 (up by 1).
  final freq = AdaptiveTrack.frequency();
  check('freq no move after 1 correct', freq.submit(true) == 6);
  check('freq harder after 2 correct (down by 2)', freq.submit(true) == 4);
  check('freq easier after wrong (up by reduced 1)', freq.submit(false) == 5);

  // 2d) Target proportion-correct points (Levitt, 1971, Table II).
  check('2-down/1-up targets ~0.707',
      (AdaptiveTrack.snr().targetProportion - 0.7071067811865476).abs() < 1e-9);
  check(
      '3-down/1-up targets ~0.794',
      (AdaptiveTrack(value: 0, min: -9, max: 9, step: 1, ruleCorrect: 3)
                  .targetProportion -
              0.7937005259840998)
          .abs() <
          1e-9);

  // 3) SpeechInNoiseSession drives the same adaptation and scores it.
  final session = SpeechInNoiseSession(
    moduleId: 'noise',
    groupId: 'sentence_noise',
    maxTrials: 1000, // let reversals govern, matching the golden run
  );
  for (final correct in kSeq) {
    final trial = FourAlternativeTrial(
      choices: const ['a', 'b', 'c', 'd'],
      targetIndex: 0,
    );
    session.submit(trial, correct ? 0 : 1, latencyMs: 500);
  }
  check(
    'session reversals match golden',
    listEqDouble(session.track.reversals, kReversals),
  );
  check(
    'session threshold matches golden',
    (session.thresholdSnrDb! - kThreshold).abs() < 1e-9,
  );
  check('session completed all trials', session.completedTrials == kSeq.length);
  final expectedCorrect = kSeq.where((c) => c).length; // 16
  check(
    'session accuracy matches',
    (session.accuracy - expectedCorrect / kSeq.length).abs() < 1e-9,
  );

  // 4) Presentation SNR is recorded per trial (first at start, last at TRAJ[-2]).
  check(
    'first trial presented at start SNR 12',
    session.records.first.parameters['snr_db'] == 12,
  );
  check(
    'last trial presented at prior post-submit SNR',
    session.records.last.parameters['snr_db'] == kTraj[kTraj.length - 2],
  );

  // 5) 4AFC generator is deterministic and well-formed.
  final t1 = FourAfcGenerator(const [
    'one',
    'two',
    'three',
    'four',
    'five',
  ], seed: 42)
      .next();
  final t2 = FourAfcGenerator(const [
    'one',
    'two',
    'three',
    'four',
    'five',
  ], seed: 42)
      .next();
  check(
    'generator deterministic for same seed',
    t1.choices.join(',') == t2.choices.join(',') &&
        t1.targetIndex == t2.targetIndex,
  );
  check('generator yields 4 distinct choices', t1.choices.toSet().length == 4);
  check('target is within choices', t1.target == t1.choices[t1.targetIndex]);

  // 6) SAFETY: trial event carries SNR, never a volume instruction.
  final json = session.records.first.toJson();
  check(
    'trial json has no volume key',
    !json.keys.any((k) => k.toLowerCase().contains('volume')),
  );
  check(
    'trial json parameters carry snr_db',
    (json['parameters'] as Map)['snr_db'] != null,
  );

  stdout.writeln('');
  if (_failures == 0) {
    stdout.writeln('PASS $_checks/$_checks engine checks');
    exit(0);
  } else {
    stdout.writeln('FAILED $_failures/$_checks engine checks');
    exit(1);
  }
}
