/// Deterministic adaptive protocol engine (pure Dart).
///
/// This is the Dart mirror of `packages/protocol_engine/engine.py`. It owns the
/// staircase adaptation, reversal tracking, stopping and threshold — the locked,
/// deterministic core of measurement. It is intentionally free of any Flutter
/// or audio dependency and is verified against a golden vector generated by the
/// Python engine (see `tool/verify/engine_harness.dart` and
/// `tests/test_engine_golden.py`).
///
/// SAFETY: adaptation moves a task parameter (e.g. SNR in dB), never master
/// volume. There is deliberately no volume field here.
library;

import 'dart:math' as math;

/// A transformed up/down staircase (default 2-down / 1-up).
///
/// Mirrors `engine.Staircase` for the `harder == 'down'` case used by every
/// current protocol (SNR, gap, modulation), where two correct answers make the
/// task harder (value decreases) and one wrong answer makes it easier.
///
/// The staircase optionally reduces its step size after the first few reversals
/// (Levitt, 1971, JASA 49:467–477: a coarse initial step converges quickly,
/// then a finer step brackets threshold more precisely). With [stepFactor] == 1
/// the step is fixed, reproducing the classic single-step staircase.
class AdaptiveTrack {
  AdaptiveTrack({
    required this.value,
    required this.min,
    required this.max,
    required this.step,
    this.twoDownOneUp = true,
    this.ruleCorrect = 2,
    this.stopReversals = 8,
    this.thresholdReversals = 6,
    this.stepFactor = 1.0,
    this.stepReductionReversals = 0,
    double? minStep,
  })  : minStep = minStep ?? step,
        currentStep = step;

  /// Speech-in-noise SNR staircase: mirrors `engine.snr_staircase`.
  ///
  /// Intentionally a fixed-step staircase — with the default [start] (12) and
  /// [step] (2) this is the golden-pinned reference trajectory shared with the
  /// Python engine. The difficulty-level system may pass a different starting
  /// SNR and step size at launch; the defaults (and therefore the golden
  /// vector) are unchanged.
  AdaptiveTrack.snr({double start = 12, double step = 2})
      : this(value: start, min: -12, max: 20, step: step);

  /// Temporal gap-detection staircase: mirrors `engine.gap_staircase`.
  ///
  /// Uses Levitt step reduction (coarse 4 ms → fine 1 ms) for a more precise
  /// gap-detection threshold, consistent with adaptive GIN-style procedures.
  AdaptiveTrack.gap({double startMs = 20})
      : this(
          value: startMs,
          min: 0.5,
          max: 100,
          step: 4,
          stepFactor: 0.5,
          stepReductionReversals: 2,
          minStep: 1,
        );

  /// Amplitude-modulation-depth staircase: mirrors `engine.modulation_staircase`.
  ///
  /// Levitt step reduction (4 dB → 1 dB) for a finer modulation-depth threshold
  /// (cf. Viemeister, 1979; Bacon & Viemeister, 1985 TMTF procedures).
  AdaptiveTrack.modulation({double startDb = -6})
      : this(
          value: startDb,
          min: -40,
          max: 0,
          step: 4,
          stepFactor: 0.5,
          stepReductionReversals: 2,
          minStep: 1,
        );

  /// Frequency / pitch-discrimination staircase (semitones).
  ///
  /// Levitt step reduction (2 st → 0.25 st) toward a difference-limen-for-
  /// frequency estimate (cf. Wier, Jesteadt & Green, 1977).
  AdaptiveTrack.frequency({double startSemitones = 6})
      : this(
          value: startSemitones,
          min: 0.25,
          max: 12,
          step: 2,
          stepFactor: 0.5,
          stepReductionReversals: 2,
          minStep: 0.25,
        );

  double value;
  final double min;
  final double max;
  final double step;

  /// When true, requires [ruleCorrect] consecutive correct answers before the
  /// task is made harder (classic transformed staircase). When false, a single
  /// correct answer moves toward harder.
  final bool twoDownOneUp;
  final int ruleCorrect;

  /// Number of reversals that ends the run.
  final int stopReversals;

  /// Number of trailing reversals averaged for the [threshold].
  final int thresholdReversals;

  /// Multiplier applied to [currentStep] at each of the first
  /// [stepReductionReversals] reversals (Levitt, 1971). 1.0 = fixed step.
  final double stepFactor;
  final int stepReductionReversals;

  /// Floor for the (reducible) step size.
  final double minStep;

  /// The step size currently in effect (starts at [step], shrinks toward
  /// [minStep] as the early reversals accrue).
  double currentStep;

  int streak = 0;
  int lastDirection = 0;
  int trials = 0;
  final List<double> reversals = <double>[];

  /// Submits one response and returns the (possibly unchanged) new [value].
  ///
  /// direction: -1 makes the task harder, +1 makes it easier. A reversal is
  /// recorded (at the value *before* the move) whenever the direction flips.
  double submit(bool correct) {
    trials++;
    var direction = 0;
    if (correct) {
      streak++;
      if (!twoDownOneUp || streak >= ruleCorrect) {
        direction = -1;
        streak = 0;
      }
    } else {
      streak = 0;
      direction = 1;
    }
    if (direction != 0) {
      if (lastDirection != 0 && direction != lastDirection) {
        reversals.add(value);
        // Levitt (1971): shrink the step over the first few reversals so the
        // measurement phase brackets threshold more finely.
        if (reversals.length <= stepReductionReversals) {
          currentStep = math.max(minStep, currentStep * stepFactor);
        }
      }
      lastDirection = direction;
      value = (value + direction * currentStep).clamp(min, max).toDouble();
    }
    return value;
  }

  /// Whether the stop rule (enough reversals) has been reached.
  bool get complete => reversals.length >= stopReversals;

  /// The proportion-correct point this rule converges on (Levitt, 1971):
  /// P = 0.5^(1/ruleCorrect) for an n-down/1-up rule (e.g. 2-down/1-up ≈ 0.707,
  /// 3-down/1-up ≈ 0.794); 0.5 for a simple 1-down/1-up rule.
  double get targetProportion =>
      twoDownOneUp ? math.pow(0.5, 1 / ruleCorrect).toDouble() : 0.5;

  /// Mean of the last [thresholdReversals] reversals, or null if too few.
  ///
  /// With step reduction the trailing reversals fall in the fine-step
  /// measurement phase, which is exactly the phase whose average estimates
  /// threshold (Levitt, 1971).
  double? get threshold {
    if (reversals.length < thresholdReversals) return null;
    final last = reversals.sublist(reversals.length - thresholdReversals);
    return last.reduce((a, b) => a + b) / last.length;
  }

  /// Standard deviation of the reversals averaged for [threshold] — a measure
  /// of threshold precision (smaller = a more reliable estimate). Reported
  /// alongside the threshold as a research-only confidence indicator; null if
  /// too few reversals.
  double? get thresholdSd {
    if (reversals.length < thresholdReversals) return null;
    final last = reversals.sublist(reversals.length - thresholdReversals);
    final m = last.reduce((a, b) => a + b) / last.length;
    final v = last.map((x) => (x - m) * (x - m)).reduce((a, b) => a + b) /
        last.length;
    return math.sqrt(v);
  }
}

/// A single completed trial's event record.
class TrialRecord {
  TrialRecord({
    required this.target,
    required this.response,
    required this.correct,
    required this.latencyMs,
    this.replays = 0,
    this.parameters = const <String, Object?>{},
  });

  final String target;
  final String response;
  final bool correct;
  final int latencyMs;
  final int replays;

  /// Protocol parameters in effect for this trial (e.g. `{'snr_db': 8}`).
  final Map<String, Object?> parameters;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'target': target,
        'response': response,
        'correct': correct,
        'latency_ms': latencyMs,
        'replay_count': replays,
        if (parameters.isNotEmpty) 'parameters': parameters,
      };
}

/// Marks the most recent trial as user-flagged ("I was distracted / that one
/// didn't count") by replacing it with a copy whose parameters carry
/// `flagged: true`. Informational only — the response has already been
/// scored and adapted on; the flag just travels with the exported record so
/// a reviewer can discount it. Returns false when there is nothing to flag.
bool flagLastTrial(List<TrialRecord> records) {
  if (records.isEmpty) return false;
  final last = records.last;
  records[records.length - 1] = TrialRecord(
    target: last.target,
    response: last.response,
    correct: last.correct,
    latencyMs: last.latencyMs,
    replays: last.replays,
    parameters: <String, Object?>{...last.parameters, 'flagged': true},
  );
  return true;
}

/// Whether the most recent trial carries the user flag.
bool lastTrialFlagged(List<TrialRecord> records) =>
    records.isNotEmpty && records.last.parameters['flagged'] == true;
